#!/bin/sh
workingDir=$(cat <<'BABEL_TABLE'
d:/Users/fni/src/emacs-leuven/
BABEL_TABLE
)
TESTEL=
TESTFILE=~/test.el
if test -e $TESTFILE # file exists
then
    TESTEL="-l $TESTFILE"
fi

EMACS="/cygdrive/c/Program\ Files\ \(x86\)/emacs-r114715-20131019-w32/bin/emacs"

# no init file
cmd="$EMACS -q -l ${workingDir}.emacs-minimal.el $TESTEL"

echo "Launching '$cmd'..."
eval "$cmd"

echo "Exit status: $?"
