#!/bin/sh
TESTEL=
TESTFILE=~/test.el
if test -e $TESTFILE # file exists
then
    TESTEL="-l $TESTFILE"
fi

EMACS="/cygdrive/c/Program\ Files\ \(x86\)/emacs-trunk/bin/emacs"

# No init file.
cmd="$EMACS -q -l ${workingDir}.emacs-minimal.el $TESTEL"

echo "Launching '$cmd'..."
eval "$cmd"

echo "Exit status: $?"
