EMACS ?= emacs

ELISP_DIRS := lisp
ELISP_FILES := $(foreach dir,$(ELISP_DIRS),$(wildcard $(dir)/*.el))

.PHONY: all check check-parens compile clean

# Run all validation and compilation targets.
all: check compile

# Run the source checks.
check: check-parens

# Check parentheses in every Emacs Lisp source file.
check-parens:
	@$(EMACS) --batch --quick --eval "(dolist (directory (list \"lisp\")) (dolist (file (directory-files-recursively directory \"\\\\.el\")) (with-temp-buffer (emacs-lisp-mode) (message \"Checking %s\" file) (insert-file-contents file) (check-parens))))"

# Byte-compile the Emacs Lisp source files.
compile:
	$(EMACS) --batch --quick -L lisp -L site-lisp -f batch-byte-compile $(ELISP_FILES)

# Remove generated byte-compiled files.
clean:
	find $(ELISP_DIRS) -type f -name '*.elc' -delete
