EMACS ?= emacs

ELISP_DIRS := lisp
ELISP_FILES := $(foreach dir,$(ELISP_DIRS),$(wildcard $(dir)/*.el))

.PHONY: all check check-parens compile clean help tangle

# Describe the available Makefile targets.
help:
	@awk '/^[[:space:]]*#[[:space:]]/ { description = $$0; sub(/^[[:space:]]*#[[:space:]]*/, "", description); next } /^[^[:space:]#A-Z]+:/ { target = $$0; sub(/:.*/, ":", target); if (description != "") printf "%-32s # %s\n", target, description; description = ""; next } { description = "" }' [Mm]akefile

# Tangle every .org and .txt file in the repository.
tangle:
	$(EMACS) --batch --quick --eval "(progn (require 'org) (require 'ob-tangle) (dolist (file (directory-files-recursively default-directory \".*\")) (when (member (file-name-extension file) '(\"org\" \"txt\")) (message \"Tangling %s\" file) (condition-case error (with-temp-buffer (insert-file-contents file) (org-mode) (setq buffer-file-name file) (org-babel-tangle)) (error (message \"Failed to tangle %s: %s\" file (error-message-string error)))))))"

# Run all validation and compilation targets.
all: check compile

# Run the source checks.
check: check-parens

# Check parentheses in every Emacs Lisp source file.
check-parens:
	@$(EMACS) --batch --quick --eval "(dolist (directory (list \"lisp\")) (dolist (file (directory-files-recursively directory \"\\\\.el\\\\'\")) (with-temp-buffer (emacs-lisp-mode) (message \"Checking %s\" file) (insert-file-contents file) (check-parens))))"

# Byte-compile the Emacs Lisp source files.
compile:
	$(EMACS) --batch --quick -L lisp -L site-lisp -f batch-byte-compile $(ELISP_FILES)

# Remove generated byte-compiled files.
clean:
	find $(ELISP_DIRS) -type f -name '*.elc' -delete
