#+TITLE:     Inbox
#+AUTHOR:    Fabrice Niessen
#+EMAIL:     (concat "fni" at-sign "pirilampo.be")
#+DESCRIPTION: A place to collect new thoughts and tasks quickly for later organization and completion.
#+KEYWORDS:  organization, tasks, thoughts, inbox
#+LANGUAGE:  en
#+OPTIONS:   ^:{}

#+FILETAGS:  :inbox:
#+SETUPFILE: ~/org/theme-readtheorg.setup

Now, *collect* all your "stuff" (new thoughts and tasks) quickly in here.

Later, sort them, organize them... and Get Them Done.

* Calendar

Appointments, events, and time-specific actions that need to be scheduled or
attended.

* Phone calls                                                             :call:
:PROPERTIES:
:CATEGORY: 0-Phone
:END:

Phone calls that need to be made or followed up on.

* Messages                                                                :mail:

Email or text messages that need to be sent or responded to.

* Shopping
:PROPERTIES:
:CATEGORY: 0-Shopping
:END:

Items that need to be purchased.

* Tasks
:PROPERTIES:
:CATEGORY: 0-Tasks
:END:

General tasks that need to be done:

Nothing for now...

* Routines

Regular, recurring tasks and habits that need to be maintained.

** Daily

** Weekly

** Monthly

** Quarterly

** Semiannually

** Yearly

** Inactive

* Checklists

Lists of steps or items to ensure completeness in various activities and tasks.

* Reading list

* Notes

Information, ideas, and reference material that need to be captured and
organized.

